apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-source
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-source
  source:
    repoURL: https://github.com/ahsanhussain-max/aom-gitops-demo
    targetRevision: dev
    path: apps/postgres-source/manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
