apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: dagster

  sources:
    - repoURL: https://dagster-io.github.io/helm
      chart: dagster
      targetRevision: 1.13.3
      helm:
        releaseName: dagster
        valueFiles:
          - $values/apps/dagster/values.yaml

    - repoURL: https://github.com/ahsanhussain-max/aom-gitops-demo
      targetRevision: dev
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
