dagster-user-deployments:
  enabled: true
  deployments:
    - name: dummy-aom
      image:
        repository: dummy-aom
        tag: "0.2"
        pullPolicy: IfNotPresent
      dagsterApiGrpcArgs:
        - "-f"
        - "definitions.py"
      port: 4000
      env:
        DATABASE_URL: "postgresql://aom:aom_dev@host.minikube.internal:5433/aom_practice"
      includeConfigInLaunchedRuns:
        enabled: true

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envConfigMaps:
        - name: dummy-aom-env
      envSecrets: []

dagsterWebserver:
  replicaCount: 2

dagsterDaemon:
  enabled: true

postgresql:
  enabled: true

ingress:
  enabled: false
