global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/minio
  tag: 2025.7.23-debian-12-r3

clientImage:
  registry: docker.io
  repository: bitnamilegacy/minio-client
  tag: 2025.5.21-debian-12-r4

mode: standalone

auth:
  rootUser: admin
  rootPassword: admin12345

persistence:
  enabled: false

defaultBuckets: "practice"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi

metrics:
  enabled: false

ingress:
  enabled: true
  hostname: minio.local
  ingressClassName: nginx
  tls: false

apiIngress:
  enabled: true
  hostname: minio-api.local
  ingressClassName: nginx
  tls: false
